### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by GatoCreador887** [Tommsy64/SmartMovingReloaded#2]
The game crashes instantly after a few seconds of loading the game. Here's the log file:
[latest.log](https://github.com/Tommsy64/SmartMovingReloaded/files/2149934/latest.log)
Is this because I don't have Sponge installed?

**Edit**:
Sponge did not fix the problem.

**Comment by PhysicalNova** [comment]
(I'm not the creator of the mod)
Please be aware that this mod is in a really early stage. Please look at the other issue which talks about the developpement of the mod. 
Have a nice day.
